-- +--------------------------------------------------------------------+
-- | Copyright CiviCRM LLC. All rights reserved.                        |
-- |                                                                    |
-- | This work is published under the GNU AGPLv3 license with some      |
-- | permitted exceptions and without any warranty. For full license    |
-- | and copyright information, see https://civicrm.org/licensing       |
-- +--------------------------------------------------------------------+
--
-- Generated from schema.tpl
-- DO NOT EDIT.  Generated by CRM_Core_CodeGen
--


-- +--------------------------------------------------------------------+
-- | Copyright CiviCRM LLC. All rights reserved.                        |
-- |                                                                    |
-- | This work is published under the GNU AGPLv3 license with some      |
-- | permitted exceptions and without any warranty. For full license    |
-- | and copyright information, see https://civicrm.org/licensing       |
-- +--------------------------------------------------------------------+
--
-- Generated from drop.tpl
-- DO NOT EDIT.  Generated by CRM_Core_CodeGen
--
-- /*******************************************************
-- *
-- * Clean up the exisiting tables
-- *
-- *******************************************************/

SET FOREIGN_KEY_CHECKS=0;

DROP TABLE IF EXISTS `civicrm_custom_templates`;

SET FOREIGN_KEY_CHECKS=1;
-- /*******************************************************
-- *
-- * Create new tables
-- *
-- *******************************************************/

-- /*******************************************************
-- *
-- * civicrm_custom_templates
-- *
-- * Table to collect system workflow templates
-- *
-- *******************************************************/
CREATE TABLE `civicrm_custom_templates` (


     `id` int unsigned NOT NULL AUTO_INCREMENT  COMMENT 'Unique CustomTemplates ID',
     `msg_title` varchar(128)    COMMENT 'message title',
     `msg_template` longtext    COMMENT 'message template' 
,
        PRIMARY KEY (`id`)
 
 
 
)    ;

INSERT INTO `civicrm_custom_templates` (`id`,`msg_title`,`msg_template`) VALUES (NULL,`datacheck`,`<mjml></mjml>`);
